name: HealthAppTransfer
options:
  bundleIdPrefix: com.caseysimon
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  CocoaMQTT:
    url: https://github.com/emqx/CocoaMQTT.git
    from: "2.1.6"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  HealthAppTransfer:
    type: application
    supportedDestinations: [iOS, macOS]
    sources:
      - path: HealthAppTransfer
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: HealthAppTransfer/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: HealthAppTransfer/App/HealthAppTransfer.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.caseysimon.HealthAppTransfer
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: HealthAppTransfer
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_EMIT_LOC_STRINGS: "YES"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: CocoaMQTT
    entitlements:
      path: HealthAppTransfer/App/HealthAppTransfer.entitlements
    info:
      path: HealthAppTransfer/App/Info.plist
      properties:
        NSHealthShareUsageDescription: "This app needs access to your health data to transfer it between devices."
        NSFaceIDUsageDescription: "This app uses Face ID to protect access to your health data and sensitive settings."
        NSLocalNetworkUsageDescription: "This app uses the local network to discover and transfer health data to nearby devices."
        UIBackgroundModes:
          - processing
        NSBonjourServices:
          - "_healthsync._tcp"

  HealthAppTransferTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS]
    sources:
      - path: HealthAppTransferTests
    dependencies:
      - target: HealthAppTransfer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  HealthAppTransferUITests:
    type: bundle.ui-testing
    supportedDestinations: [iOS, macOS]
    sources:
      - path: HealthAppTransferUITests
    dependencies:
      - target: HealthAppTransfer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
