name: HealthAppTransfer
options:
  bundleIdPrefix: com.caseysimon
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  CocoaMQTT:
    url: https://github.com/emqx/CocoaMQTT.git
    from: "2.1.6"

settings:
  base:
    SWIFT_VERSION: "5.9"

schemes:
  HealthAppTransfer:
    build:
      targets:
        HealthAppTransfer: all
        HealthAppTransferTests: [test]
        HealthAppTransferUITests: [test]
    test:
      targets:
        - HealthAppTransferTests
        - HealthAppTransferUITests

targets:
  HealthAppTransfer:
    type: application
    supportedDestinations: [iOS, macOS]
    sources:
      - path: HealthAppTransfer
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: HealthAppTransfer/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: HealthAppTransfer/App/HealthAppTransfer.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.caseysimon.HealthAppTransfer
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_KEY_CFBundleDisplayName: HealthAppTransfer
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_EMIT_LOC_STRINGS: "YES"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: CocoaMQTT
      - target: HealthAppTransferWidget
    entitlements:
      path: HealthAppTransfer/App/HealthAppTransfer.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.caseysimon.HealthAppTransfer
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.caseysimon.HealthAppTransfer
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.caseysimon.HealthAppTransfer
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.healthkit.background-delivery: true
    info:
      path: HealthAppTransfer/App/Info.plist
      properties:
        NSHealthShareUsageDescription: "This app needs access to your health data to transfer it between devices."
        NSFaceIDUsageDescription: "This app uses Face ID to protect access to your health data and sensitive settings."
        NSLocalNetworkUsageDescription: "This app uses the local network to discover and transfer health data to nearby devices."
        NSSupportsLiveActivities: true
        UIBackgroundModes:
          - fetch
          - processing
        BGTaskSchedulerPermittedIdentifiers:
          - com.caseysimon.HealthAppTransfer.refresh
          - com.caseysimon.HealthAppTransfer.export
        LSSupportsOpeningDocumentsInPlace: true
        NSCalendarsFullAccessUsageDescription: "This app creates calendar events for your workouts when the Calendar automation is enabled."
        NSBonjourServices:
          - "_healthsync._tcp"
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: com.topografix.gpx
            UTTypeDescription: GPS Exchange Format
            UTTypeConformsTo:
              - public.xml
            UTTypeTagSpecification:
              public.filename-extension:
                - gpx
              public.mime-type:
                - application/gpx+xml
        CFBundleDocumentTypes:
          - CFBundleTypeName: JSON
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.json
          - CFBundleTypeName: CSV
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.comma-separated-values-text
          - CFBundleTypeName: GPX
            LSHandlerRank: Owner
            LSItemContentTypes:
              - com.topografix.gpx

  HealthAppTransferWidget:
    type: app-extension
    supportedDestinations: [iOS]
    sources:
      - path: HealthAppTransferWidget
        excludes:
          - "Info.plist"
          - "HealthAppTransferWidget.entitlements"
      - path: HealthAppTransfer/Models/SyncActivityAttributes.swift
      - path: HealthAppTransfer/Models/HealthDataType.swift
      - path: HealthAppTransfer/Models/WidgetMetricSnapshot.swift
      - path: HealthAppTransfer/Services/Widget/WidgetDataStore.swift
    settings:
      base:
        INFOPLIST_FILE: HealthAppTransferWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: HealthAppTransferWidget/HealthAppTransferWidget.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.caseysimon.HealthAppTransfer.Widget
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_EMIT_LOC_STRINGS: "YES"
    entitlements:
      path: HealthAppTransferWidget/HealthAppTransferWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.caseysimon.HealthAppTransfer
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    dependencies:
      - sdk: HealthKit.framework
    info:
      path: HealthAppTransferWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  HealthAppTransferTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS]
    sources:
      - path: HealthAppTransferTests
    dependencies:
      - target: HealthAppTransfer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  HealthAppTransferUITests:
    type: bundle.ui-testing
    supportedDestinations: [iOS, macOS]
    sources:
      - path: HealthAppTransferUITests
    dependencies:
      - target: HealthAppTransfer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
